CAT_TEMPLATE = 'https://kpolyakov.spb.ru/school/ege/gen.php?action=listCategories&egeId=%d'
SEARCH_TEMPLATE = 'https://kpolyakov.spb.ru/school/ege/gen.php?action=viewTopic&topicId=%d'
ALL_TEMPLATE = 'https://kpolyakov.spb.ru/school/ege/gen.php?action=viewAllEgeNo&egeId=%d'
FILE_PREFIX = 'https://kpolyakov.spb.ru/cms/files/%s'
IMAGE_PREFIX = 'https://kpolyakov.spb.ru/cms/images/%s'
